### ISSUE TITLE
Conditional Image in Lightbox or something similar?

### ISSUE THREAD

**Issue by Mylezman** [somewherewarm/woocommerce-composite-products-conditional-images#6]
Is there any way to have the Conditional Image work in Lightbox or something similar where we can display the composite product assembly and its corresponding conditional image in the same window and ideally separate everything else?

For Example:
https://m2inc.biz/product/1%e2%80%b3x18-ladder-straps-riveted-to-extensions-copy/

**Comment by manospsyx** [comment]
cc @jimjasson 😇

**Comment by jimjasson** [comment]
Hey @Mylezman 👋

> For Example: https://m2inc.biz/product/1%e2%80%b3x18-ladder-straps-riveted-to-extensions-copy/

I visited this link but it redirected me to a 404 page. Perhaps only site admins have access to this product for the time being? 

> Is there any way to have the Conditional Image work in Lightbox or something similar

Are you using Scenarios to [swap](https://github.com/somewherewarm/woocommerce-composite-products-conditional-images#image-swapping-1) the main product image or [compose](https://github.com/somewherewarm/woocommerce-composite-products-conditional-images#image-compositing-1) a new one?

If it is the latter, then the Conditional Images mini-extension overlays the images you add in each Scenario on top of the main Composite Product image -- it doesn't create a new, **assembled** image based on the component selections. Therefore, the image you see in [this example](https://user-images.githubusercontent.com/1783726/60344163-91c5b500-99be-11e9-8640-4ab24c855d97.png) is not a standalone image in your media library that can be opened in a lightbox window. 

If it is the former, then to apply your theme's lightbox features on the overridden Composite Product image it is necessary to wrap the overridden image around `<a>` tags that point to the image's URL in your media library. 

To do this, you need to:
1. Unhook this function: https://github.com/somewherewarm/woocommerce-composite-products-conditional-images/blob/master/composite-products-conditional-images-for-woocommerce.php#L112
2. Hook your own custom function in the same filter. 
3. In your custom function add `<a>` tags around the image HTML: https://github.com/somewherewarm/woocommerce-composite-products-conditional-images/blob/master/composite-products-conditional-images-for-woocommerce.php#L284

If you need further help with this customization, then I'd suggest working with an experienced WooCommerce developer.

**Comment by Mylezman** [comment]
Hello Jason,

Sorry, I forgot the product I sent you was 'private'

*Here
<https://m2inc.biz/product/0-75-thermoplastic-ratcheting-buckles-on-extensions-test/#buckles>*is
an example of how we would like the featured image to change through every
step of the assembly process by overlaying images to create a final
composition of the assembly.
(Click the 'Assemble & Buy' Tab to view and initiate the assembly process).

I believe we are using Scenarios to compose
<https://github.com/somewherewarm/woocommerce-composite-products-conditional-images#image-compositing-1>
a
new featured image.

We would like the featured image in the lower right corner of the Composite
Products 'Assemble and Buy' Widget on *this page
<https://m2inc.biz/product/0-75-thermoplastic-ratcheting-buckles-on-extensions-test-lightroom/#review>
*to be responsive just like the featured image in the link above if
possible; (See Image for exact location)
Can this image be responsive and update as customers make their selections,
or update at the very end of the assembly process?
If not,  is there a way to have the clickable images show up *ON TOP* of
the Lightbox (*Note:* the actual featured image* DOES* update on this
product page, but is behind the Lightbox);
or a layout so customers can see *both *the responsive featured image and
each step of the assembly process on the same screen?

Will this process work?  (I wasn't totally sure if this was for swapped
images or composed images)

   1. Unhook this function:
   https://github.com/somewherewarm/woocommerce-composite-products-conditional-images/blob/master/composite-products-conditional-images-for-woocommerce.php#L112
   2. Hook your own custom function in the same filter.
   3. In your custom function add <a> tags around the image HTML:
   https://github.com/somewherewarm/woocommerce-composite-products-conditional-images/blob/master/composite-products-conditional-images-for-woocommerce.php#L284

.

We really like this plug-in's ability to showcase customers' finished
custom assembly, but would like to layout it out in a way so customers can
see their selections and the featured image update in live time all on the
same screen w/out having to scroll or close the lightbox.

Thank you so much for your help and support!

-Myles Moran

**Comment by jimjasson** [comment]
Hey @Mylezman -- thank you for the additional details! 

Taking a look at this Composite Product: https://m2inc.biz/product/0-75-thermoplastic-ratcheting-buckles-on-extensions-test-lightroom/#buckles, I noticed that you have added some custom code to display the components form in a popup window when the `Assemble and Buy` button is clicked: https://d.pr/v/MGkVFr.

In this popup window, you have also added an image that you'd like to: 
- update based on the component selections and also;
- be able to preview this image in a lightbox window. 

Here's a screenshot of this image: https://d.pr/i/d3ovaE.

The Conditional Images mini-extension targets only the main Composite Product image out of the box. If you'd like to use this plugin to update a custom image, then it is necessary to write significant custom code. 

Moreover, you are right that when you click on this extra image you added, then this image opens up in a popup window but behind the popup window that contains the component options. This seems to be a conflict between the theme's lightbox feature and the custom code you have added to move the components form in a dedicated popup. 

If you need help with resolving this conflict or extending the Conditional Images mini-extension to work on images other than the main Composite image, then I would suggest working closely with a dedicated WooCommerce developer. [Codeable](https://www.codeable.io/) and [WooCommerce Experts](https://woocommerce.com/search/?collections=service) are both great resources for finding a developer for this project.
